---
title: "ETC1010-5510 Project  Milestone 1 - T11_Wed_skimr"
subtitle: "A Report On The LinkedIn-World Bank Digital Data for Development"
author: "Hanchen Wang (30704456), Hao Li (32041594), Jiaying Zhang (30930685), Mohammed Faizan (31939872), Karan Garg (32106580)"
output: 
  bookdown::html_document2
keep_md: true
---


**TUTOR: Samantha Dawson**

**LECTURER: Patricia Menéndez**

# Project and Data Description

## The LinkedIn-World Bank Digital Data for Development: Industry Jobs and Skills Trends

"The World Bank Group and LinkedIn have created the Digital Data for Development collaboration to support innovative policy decisions as developing countries grapple with a rapidly changing global economy. With hundreds of millions of members worldwide, LinkedIn has the potential to offer a new, timely, and granular source of data about emerging industries, workers’ changing skills composition and how they’re engaging with labor markets globally." ~ [1](https://linkedindata.worldbank.org/about)

This collaboration enables government and policy makers to drive better policy implementations,  thus creating opportunities to the global work force. The data represents LinkedIn members' data based on four metrics: Industry Employment Shifts, Talent Migration, Industry Skills Needs and Skills Penetration. The records in the data represent over 100 countries having a distribution across six major industry sectors(representing 148 industries): Financial Services, Professional Services, Information & Communication Technology (ICT), the Arts & Creative Industries, Manufacturing, and Mining/Quarrying and possessing skills within the over 50,000 distinct, standardized skills classified by LinkedIn into 249 skill groups, further categorised as: Business Skills, Disruptive Tech Skills, Soft Skills, Specialized Industry Skills and Tech Skills.  

For our project, we will be working on the following questions.

## Data Source

1) [The LinkedIn-World Bank Digital Data for Development:Industry Jobs and Skills Trends - About](https://linkedindata.worldbank.org/about)
 
2) [The World Bank: Industry Skills Needs Dataset(3500 X 7), Skill Penetration Dataset(20780 X 7)](https://datacatalog.worldbank.org/dataset/skills-linkedin-data)

3) [The World Bank: Talent Migration Dataset(Industry Migration-5295 X 13)](https://datacatalog.worldbank.org/dataset/talent-migration-linkedin-data)

4) [The World Bank: Industry Employment Shifts Dataset(7335 X 13)](https://datacatalog.worldbank.org/dataset/employment-growth-linkedin-data)

5) [The World Bank: Terms of Use for Datasets(CC BY 4.0)](https://www.worldbank.org/en/about/legal/terms-of-use-for-datasets)

## Questions

Q1) Which skill category is most common across all Industry Sections and how does it vary between each section? **(Hao Li)**

Q2) What is the average percentage of net migration for each industry over the past five years and is the growth rate of immigration within the industry related to the growth rate of the industry? **(Jiaying Zhang)**

Q3) For each industry_section, which industry has the highest penetration rate for the most common skill_category? **((Hanchen Wang)**

Q4) Find the industry_section that is best to each region/continent. **(Faizan & Karan)**

Q5) Which industry_name sees the maximum growth over time in each region/continent , depending on the region’s best industry_section ? **(Mohammed Faizan)**

Q6) For each region, which country did the above found industry had had maximum growth? And, what is the income group of that nation? **(Karan Garg)**



